name: Java CI with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 16

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: build-tools
        run: sdkmanager "build-tools;30.0.3"

      - name: Add Android SDK to PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: informatis
          path: build/libs/*.jar
